name: yanalytics
description: Y-Analytics implementation for dart and flutter projects
version: 1.0.0
repository: https://github.com/yml-org/yanalytics-flutter

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
