name: Document
on:
  push:
    branches: [ main ]
jobs:
  generate_documentation:
    env:
      working-directory: ./app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.11"
      - name: "Install dartdoc"
        run: flutter pub global activate dartdoc
      - name: "Generate documentation"
        run: flutter pub global run dartdoc --output docs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated documentation

