name: Test
# Trigger the workflow on push or pull request
on: [push, pull_request]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  lint_and_test:
    env:
      working-directory: ./app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.11"
      - name: "Lint"
        run: flutter analyze
      - name: "Run tests"
        run: flutter test
